name: "devcontainer-with-dockercompose-compose-stack"

services:

  app:
    image: "mcr.microsoft.com/devcontainers/python:1-3.12-bullseye"
    # build:
    #   context: ..
    #   dockerfile: .devcontainer/Dockerfile
    #   target: develop
    command: tail -f /dev/null
    networks:
      - custom_network

networks:
  custom_network:
    driver: bridge
